CREATE TABLE HMFMSFD.FSS_BALANCE_CFG
(
    CFG_ID            NUMBER(19)                    NOT NULL,
    ACCT_NO           VARCHAR2(32 CHAR)             NOT NULL,
    SIDE_TYPE         CHAR                          NOT NULL,
    ADJ_TYPE          CHAR                          NOT NULL,
    ITEM_CODE         VARCHAR2(32)                  NOT NULL,
    ITEM_NAME         VARCHAR2(128)                 NOT NULL,
    DEFAULT_AMT       NUMBER(18, 2) DEFAULT 0       NOT NULL,
    EFFECT_START_DATE CHAR(8)                       NOT NULL,
    EFFECT_END_DATE   CHAR(8),
    REASON            VARCHAR2(256),
    DISPLAY_ORDER     NUMBER(10)    DEFAULT 0       NOT NULL,
    IS_DEL            CHAR          DEFAULT '0'     NOT NULL,
    CREATE_TIME       DATE          DEFAULT SYSDATE NOT NULL,
    CREATE_USER       VARCHAR2(32),
    UPDATE_TIME       DATE,
    UPDATE_USER       VARCHAR2(32),
    MODIFY_PERMISSION CHAR          DEFAULT '1'     NOT NULL,
    SOURCE_TYPE       CHAR          DEFAULT '0'     NOT NULL,
    CONSTRAINT PK_FSS_BALANCE_CFG
        PRIMARY KEY ( CFG_ID ),
    CONSTRAINT UK_FSS_BALANCE_CFG
        UNIQUE ( SIDE_TYPE, ADJ_TYPE, ITEM_CODE, ACCT_NO ),
    CONSTRAINT CK_FSS_BALANCE_CFG_MODIFY_PERM
        CHECK (MODIFY_PERMISSION IN ( '0', '1' )),
    CONSTRAINT CK_FSS_BALANCE_CFG_SOURCE_TYPE
        CHECK (SOURCE_TYPE IN ( '0', '1', '2' ))
);

COMMENT ON TABLE HMFMSFD.FSS_BALANCE_CFG IS '日平衡表调整项目配置表';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.CFG_ID IS '主键ID';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.ACCT_NO IS '专户账号';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.SIDE_TYPE IS '所属侧：B-银行流水 S-维修资金系统';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.ADJ_TYPE IS '调整类型：A-应加 S-应减';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.ITEM_CODE IS '项目编码（系统内部编码）';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.ITEM_NAME IS '项目名称（如清户利息、户卡未到账）';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.DEFAULT_AMT IS '默认金额（0表示运行时计算）';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.EFFECT_START_DATE IS '生效开始日期 YYYYMMDD';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.EFFECT_END_DATE IS '生效结束日期 YYYYMMDD，可为空';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.REASON IS '原因说明';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.DISPLAY_ORDER IS '显示顺序';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.IS_DEL IS '是否删除：0-未删除，1-已删除';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.CREATE_USER IS '创建人';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.UPDATE_USER IS '最后更新人';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.MODIFY_PERMISSION IS '修改许可（0-否，1-是）';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG.SOURCE_TYPE IS '明细来源类型：0-无明细信息，1-银行侧信息，2-系统侧信息';

