CREATE TABLE HMFMSFD.FSS_BALANCE_CFG_BANK
(
    ID          NUMBER(19) DEFAULT 0       NOT NULL,
    CFG_ID      NUMBER(19) DEFAULT 0       NOT NULL,
    WATER_ID    NUMBER(19) DEFAULT 0       NOT NULL,
    CREATE_TIME DATE       DEFAULT SYSDATE NOT NULL,
    CATEGORY    VARCHAR2(512),
    REMARK      VARCHAR2(512),
    CONSTRAINT PK_FSS_BALANCE_CFG_BANK
        PRIMARY KEY ( ID )
);

COMMENT ON TABLE HMFMSFD.FSS_BALANCE_CFG_BANK IS '银行配置项明细表';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.ID IS '主键';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.CFG_ID IS '配置项ID';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.WATER_ID IS '流水ID';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.CATEGORY IS '类别';

COMMENT ON COLUMN HMFMSFD.FSS_BALANCE_CFG_BANK.REMARK IS '备注';

CREATE INDEX HMFMSFD.IDX_FSS_BALANCE_CFG_BANK_CFG
    ON HMFMSFD.FSS_BALANCE_CFG_BANK ( CFG_ID );

CREATE INDEX HMFMSFD.IDX_FSS_BALANCE_CFG_BANK_WATER
    ON HMFMSFD.FSS_BALANCE_CFG_BANK ( WATER_ID );

