CREATE TABLE FSS_BALANCE_CFG_TRADE
(
    ID              NUMBER(19)    DEFAULT 0       NOT NULL
        CONSTRAINT PK_FSS_BALANCE_CFG_TRADE
            PRIMARY KEY,
    CFG_ID          NUMBER(19)    DEFAULT 0       NOT NULL,
    INFO_ID         NUMBER(19)    DEFAULT 0,
    INFO_ADDR       VARCHAR2(512),
    OWN_NAME        VARCHAR2(512),
    OWN_REF         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_REF_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_OWN_REF_ST
            CHECK (OWN_REF_STATUS IN ( '0', '1', '2' )),
    OWN_INT         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_INT_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_OWN_INT_ST
            CHECK (OWN_INT_STATUS IN ( '0', '1', '2' )),
    DEV_NAME        VARCHAR2(512),
    DEV_REF         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_REF_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_DEV_REF_ST
            CHECK (DEV_REF_STATUS IN ( '0', '1', '2' )),
    DEV_INT         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_INT_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_DEV_INT_ST
            CHECK (DEV_INT_STATUS IN ( '0', '1', '2' )),
    REMARK          VARCHAR2(512),
    CREATE_TIME     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME     DATE,
    SOURCE_TYPE     VARCHAR2(128),
    CATEGORY        VARCHAR2(16),
    SECT_ID         NUMBER(19)    DEFAULT 0,
    OWN_CERT_TYPE   CHAR(2),
    OWN_CERT_CODE   VARCHAR2(1024),
    PRODUCE_DATE    CHAR(8),
    RAW_DETAIL_INFO VARCHAR2(2000),
    TRAN_AMT        NUMBER(16, 2),
    BATCH_NO        CHAR(12)
)
/

COMMENT ON TABLE FSS_BALANCE_CFG_TRADE IS '系统配置项明细表'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.ID IS '主键'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CFG_ID IS '配置项ID'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ID IS '信息ID'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ADDR IS '地址'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_NAME IS '购房人姓名'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF IS '购房人退款本金'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF_STATUS IS '购房人退款本金状态(0未处理/1处理中/2已处理)'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT IS '购房人退款利息'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT_STATUS IS '购房人退款利息状态(0未处理/1处理中/2已处理)'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_NAME IS '开发商名称'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF IS '开发商退款本金'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF_STATUS IS '开发商退款本金状态(0未处理/1处理中/2已处理)'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT IS '开发商退款利息'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT_STATUS IS '开发商退款利息状态(0未处理/1处理中/2已处理)'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.REMARK IS '备注'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CREATE_TIME IS '创建时间'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.SOURCE_TYPE IS '来源文件名称'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CATEGORY IS '类别'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.SECT_ID IS '项目信息Id'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_TYPE IS '购房人证件类型'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_CODE IS '购房人证件号码'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.PRODUCE_DATE IS '产生日期'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.RAW_DETAIL_INFO IS '原始明细信息'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.TRAN_AMT IS '总待退金额=未处理开发商本金+未处理开发商利息+未处理购房人本金+未处理购房人利息'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.BATCH_NO IS '业务编号'
/

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_CFG
    ON FSS_BALANCE_CFG_TRADE ( CFG_ID )
/

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_INFO
    ON FSS_BALANCE_CFG_TRADE ( INFO_ID )
/

BALANCE_CFG_TRADE ( CFG_ID );

CREATE INDEX HMFMSFD.IDX_FSS_BALANCE_CFG_TRADE_INFO
    ON HMFMSFD.FSS_BALANCE_CFG_TRADE ( INFO_ID );

