-- =========================================
-- Table: FSS_RECON_SUM
-- Desc : 专户对账主表
-- =========================================

CREATE TABLE FSS_RECON_SUM
(
    RECON_ID        NUMBER(19)                    NOT NULL,
    ACCT_NO         VARCHAR2(32 CHAR)             NOT NULL,
    RECON_NO        VARCHAR2(32 CHAR)             NOT NULL,
    RECON_DATE      CHAR(8 CHAR)                  NOT NULL,
    RECON_TYPE      CHAR(1 CHAR)                  NOT NULL,
    OPERATOR_CODE   VARCHAR2(32 CHAR)             NOT NULL,
    OPERATOR_NAME   VARCHAR2(64 CHAR),
    BANK_END_BAL    NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_END_BAL     NUMBER(18, 2) DEFAULT 0       NOT NULL,
    REAL_MATCH_FLAG CHAR(1 CHAR)  DEFAULT 'N'     NOT NULL,
    ADJ_MATCH_FLAG  CHAR(1 CHAR)  DEFAULT 'N'     NOT NULL,
    BILA_MATCH_FLAG CHAR(1 CHAR)  DEFAULT 'N'     NOT NULL,
    REMARK          VARCHAR2(256 CHAR),
    CREATE_TIME     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME     DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_FSS_RECON_SUM PRIMARY KEY ( RECON_ID ),
    CONSTRAINT UK_FSS_RECON_SUM_RECON_NO UNIQUE ( RECON_NO )
);

COMMENT ON TABLE FSS_RECON_SUM IS '专户对账主表';

COMMENT ON COLUMN FSS_RECON_SUM.RECON_ID IS '主键ID';
COMMENT ON COLUMN FSS_RECON_SUM.ACCT_NO IS '专户账号';
COMMENT ON COLUMN FSS_RECON_SUM.RECON_NO IS '对账编号(展示用，如 251203000001)';
COMMENT ON COLUMN FSS_RECON_SUM.RECON_DATE IS '对账日期时间';
COMMENT ON COLUMN FSS_RECON_SUM.RECON_TYPE IS '对账类型：A-自动，M-人工';
COMMENT ON COLUMN FSS_RECON_SUM.OPERATOR_CODE IS '操作员号';
COMMENT ON COLUMN FSS_RECON_SUM.OPERATOR_NAME IS '操作员姓名';
COMMENT ON COLUMN FSS_RECON_SUM.BANK_END_BAL IS '银行期末余额（元）';
COMMENT ON COLUMN FSS_RECON_SUM.SYS_END_BAL IS '系统期末余额（元）';
COMMENT ON COLUMN FSS_RECON_SUM.REAL_MATCH_FLAG IS '实账是否平账：Y-平 N-不平';
COMMENT ON COLUMN FSS_RECON_SUM.ADJ_MATCH_FLAG IS '调整是否平账：Y-平 N-不平';
COMMENT ON COLUMN FSS_RECON_SUM.BILA_MATCH_FLAG IS '发生是否平账：Y-平 N-不平';
COMMENT ON COLUMN FSS_RECON_SUM.REMARK IS '备注';
COMMENT ON COLUMN FSS_RECON_SUM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FSS_RECON_SUM.UPDATE_TIME IS '更新时间';

-- =========================================
-- Table: FSS_RECON_DETAILS
-- Desc : 日终平衡表主表-合并了对账明细表
-- =========================================

CREATE TABLE FSS_RECON_DETAILS
(
    SHEET_ID           NUMBER(19)                    NOT NULL,
    RECON_ID           NUMBER(19)                    NOT NULL,
    ACCT_NO            VARCHAR2(32)                  NOT NULL,
    ACCT_NAME          VARCHAR2(128),
    ORG_ID             VARCHAR2(32),
    RECON_DATE         CHAR(8)                       NOT NULL,

    BANK_BEGIN_BAL     NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_DR_AMT        NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_CR_AMT        NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_END_BAL       NUMBER(18, 2) DEFAULT 0       NOT NULL,

    SYS_BEGIN_BAL      NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_DR_AMT         NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_CR_AMT         NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_END_BAL        NUMBER(18, 2) DEFAULT 0       NOT NULL,

    BANK_BEGIN_BILA    NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_PEND_DR_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_PEND_CR_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_CLEAR_DR_AMT  NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_CLEAR_CR_AMT  NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_DR_BILA       NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_CR_BILA       NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_END_BILA      NUMBER(18, 2) DEFAULT 0       NOT NULL,

    SYS_BEGIN_BILA     NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_PEND_DR_AMT    NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_PEND_CR_AMT    NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_CLEAR_DR_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_CLEAR_CR_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_DR_BILA        NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_CR_BILA        NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_END_BILA       NUMBER(18, 2) DEFAULT 0       NOT NULL,

    BANK_ADJ_BEGIN_BAL NUMBER(18, 2) DEFAULT 0       NOT NULL,
    BANK_ADJ_END_BAL   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_ADJ_BEGIN_BAL  NUMBER(18, 2) DEFAULT 0       NOT NULL,
    SYS_ADJ_END_BAL    NUMBER(18, 2) DEFAULT 0       NOT NULL,

    BALANCE_FLAG       CHAR          DEFAULT 'N'     NOT NULL,
    BALANCE_DIFF_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,

    REMARK             VARCHAR2(512),
    CREATE_TIME        DATE          DEFAULT SYSDATE NOT NULL,
    CREATE_USER        VARCHAR2(32),
    UPDATE_TIME        DATE,
    UPDATE_USER        VARCHAR2(32),

    CONSTRAINT PK_FSS_RECON_DETAILS PRIMARY KEY ( SHEET_ID )
);

COMMENT ON TABLE FSS_RECON_DETAILS IS '日终平衡表主表-合并了对账明细表';

COMMENT ON COLUMN FSS_RECON_DETAILS.SHEET_ID IS '主键ID';
COMMENT ON COLUMN FSS_RECON_DETAILS.RECON_ID IS '来源对账ID';
COMMENT ON COLUMN FSS_RECON_DETAILS.ACCT_NO IS '专户账号';
COMMENT ON COLUMN FSS_RECON_DETAILS.ACCT_NAME IS '专户名称';
COMMENT ON COLUMN FSS_RECON_DETAILS.ORG_ID IS '管理机构ID';
COMMENT ON COLUMN FSS_RECON_DETAILS.RECON_DATE IS '对账日期 YYYYMMDD';

COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_BEGIN_BAL IS '银行期初余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_DR_AMT IS '本期借方金额（银行）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_CR_AMT IS '本期贷方金额（银行）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_END_BAL IS '银行期末余额';

COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_BEGIN_BAL IS '系统期初余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_DR_AMT IS '系统本期借方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_CR_AMT IS '系统本期贷方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_END_BAL IS '系统期末余额';

COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_BEGIN_BILA IS '银行双边期初余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_PEND_DR_AMT IS '挂账借方金额（银行侧）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_PEND_CR_AMT IS '挂账贷方金额（银行侧）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_CLEAR_DR_AMT IS '清账借方金额（银行侧）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_CLEAR_CR_AMT IS '清账贷方金额（银行侧）';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_DR_BILA IS '银行本期借方发生额';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_CR_BILA IS '银行本期贷方发生额';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_END_BILA IS '银行双边期末余额';

COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_BEGIN_BILA IS '系统双边期初余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_PEND_DR_AMT IS '系统挂账借方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_PEND_CR_AMT IS '系统挂账贷方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_CLEAR_DR_AMT IS '系统清账借方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_CLEAR_CR_AMT IS '系统清账贷方金额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_DR_BILA IS '系统本期借方发生额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_CR_BILA IS '系统本期贷方发生额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_END_BILA IS '系统双边期末余额';

COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_ADJ_BEGIN_BAL IS '银行调整前余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.BANK_ADJ_END_BAL IS '银行调整后余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_ADJ_BEGIN_BAL IS '系统调整前余额';
COMMENT ON COLUMN FSS_RECON_DETAILS.SYS_ADJ_END_BAL IS '系统调整后余额';

COMMENT ON COLUMN FSS_RECON_DETAILS.BALANCE_FLAG IS '是否平衡 Y/N';
COMMENT ON COLUMN FSS_RECON_DETAILS.BALANCE_DIFF_AMT IS '调整后余额差额（银行-系统）';

COMMENT ON COLUMN FSS_RECON_DETAILS.REMARK IS '备注说明';
COMMENT ON COLUMN FSS_RECON_DETAILS.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FSS_RECON_DETAILS.CREATE_USER IS '创建人';
COMMENT ON COLUMN FSS_RECON_DETAILS.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN FSS_RECON_DETAILS.UPDATE_USER IS '最后更新人';

CREATE INDEX IDX_FSS_DAILY_BAL_SHEET_DATE
    ON FSS_RECON_DETAILS ( RECON_DATE );

-- =========================================
-- Table: FSS_BALANCE_CFG
-- Desc : 日平衡表调整项目配置表
-- =========================================

CREATE TABLE FSS_BALANCE_CFG
(
    CFG_ID            NUMBER(19)                    NOT NULL,
    ACCT_NO           VARCHAR2(32 CHAR)             NOT NULL,
    SIDE_TYPE         CHAR                          NOT NULL,
    ADJ_TYPE          CHAR                          NOT NULL,
    ITEM_CODE         VARCHAR2(32)                  NOT NULL,
    ITEM_NAME         VARCHAR2(128)                 NOT NULL,
    DEFAULT_AMT       NUMBER(18, 2) DEFAULT 0       NOT NULL,
    EFFECT_START_DATE CHAR(8)                       NOT NULL,
    EFFECT_END_DATE   CHAR(8),
    REASON            VARCHAR2(256),
    DISPLAY_ORDER     NUMBER(10)    DEFAULT 0       NOT NULL,
    IS_DEL            CHAR          DEFAULT '0'     NOT NULL,
    CREATE_TIME       DATE          DEFAULT SYSDATE NOT NULL,
    CREATE_USER       VARCHAR2(32),
    UPDATE_TIME       DATE,
    UPDATE_USER       VARCHAR2(32),

    MODIFY_PERMISSION CHAR          DEFAULT '1'     NOT NULL,
    SOURCE_TYPE       CHAR          DEFAULT '0'     NOT NULL,

    CONSTRAINT PK_FSS_BALANCE_CFG PRIMARY KEY ( CFG_ID ),
    CONSTRAINT UK_FSS_BALANCE_CFG UNIQUE ( SIDE_TYPE, ADJ_TYPE, ITEM_CODE, ACCT_NO ),

    CONSTRAINT CK_FSS_BALANCE_CFG_MODIFY_PERM
        CHECK (MODIFY_PERMISSION IN ( '0', '1' )),

    CONSTRAINT CK_FSS_BALANCE_CFG_SOURCE_TYPE
        CHECK (SOURCE_TYPE IN ( '0', '1', '2' ))
);

COMMENT ON TABLE FSS_BALANCE_CFG IS '日平衡表调整项目配置表';

COMMENT ON COLUMN FSS_BALANCE_CFG.CFG_ID IS '主键ID';
COMMENT ON COLUMN FSS_BALANCE_CFG.ACCT_NO IS '专户账号';
COMMENT ON COLUMN FSS_BALANCE_CFG.SIDE_TYPE IS '所属侧：B-银行流水 S-维修资金系统';
COMMENT ON COLUMN FSS_BALANCE_CFG.ADJ_TYPE IS '调整类型：A-应加 S-应减';
COMMENT ON COLUMN FSS_BALANCE_CFG.ITEM_CODE IS '项目编码（系统内部编码）';
COMMENT ON COLUMN FSS_BALANCE_CFG.ITEM_NAME IS '项目名称（如清户利息、户卡未到账）';
COMMENT ON COLUMN FSS_BALANCE_CFG.DEFAULT_AMT IS '默认金额（0表示运行时计算）';
COMMENT ON COLUMN FSS_BALANCE_CFG.EFFECT_START_DATE IS '生效开始日期 YYYYMMDD';
COMMENT ON COLUMN FSS_BALANCE_CFG.EFFECT_END_DATE IS '生效结束日期 YYYYMMDD，可为空';
COMMENT ON COLUMN FSS_BALANCE_CFG.REASON IS '原因说明';
COMMENT ON COLUMN FSS_BALANCE_CFG.DISPLAY_ORDER IS '显示顺序';
COMMENT ON COLUMN FSS_BALANCE_CFG.IS_DEL IS '是否删除：0-未删除，1-已删除';
COMMENT ON COLUMN FSS_BALANCE_CFG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FSS_BALANCE_CFG.CREATE_USER IS '创建人';
COMMENT ON COLUMN FSS_BALANCE_CFG.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN FSS_BALANCE_CFG.UPDATE_USER IS '最后更新人';
COMMENT ON COLUMN FSS_BALANCE_CFG.MODIFY_PERMISSION IS '修改许可（0-否，1-是）';
COMMENT ON COLUMN FSS_BALANCE_CFG.SOURCE_TYPE IS '明细来源类型：0-无明细信息，1-银行侧信息，2-系统侧信息';

-- =========================================
-- Table: FSS_BALANCE_CFG_LOG
-- Desc : cfg.default_amt 应用状态表（按日累计幂等控制）
-- =========================================

CREATE TABLE FSS_BALANCE_CFG_LOG
(
    LOG_ID        NUMBER(19)                    NOT NULL,
    ACCT_NO       VARCHAR2(32 CHAR)             NOT NULL,
    BIZ_DATE      CHAR(8 CHAR)                  NOT NULL,
    CFG_ID        NUMBER(19)                    NOT NULL,
    APPLIED_AMT   NUMBER(18, 2) DEFAULT 0       NOT NULL,
    LAST_RECON_ID NUMBER(19),
    LAST_SHEET_ID NUMBER(19),
    LAST_ACTION   CHAR,
    CREATE_TIME   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME   DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_FSS_BALANCE_CFG_LOG PRIMARY KEY ( LOG_ID ),
    CONSTRAINT UK_FSS_BALANCE_CFG_LOG UNIQUE ( ACCT_NO, BIZ_DATE, CFG_ID )
);

COMMENT ON TABLE FSS_BALANCE_CFG_LOG IS 'cfg.default_amt 应用状态表（按日累计幂等控制）';

COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.LOG_ID IS '主键ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.ACCT_NO IS '专户账号';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.BIZ_DATE IS '业务日期 YYYYMMDD（清账发生日/统计日）';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.CFG_ID IS '配置项ID（唯一标识，关联FSS_BALANCE_CFG.CFG_ID）';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.APPLIED_AMT IS '已应用累计值（当日累计总额），用于 diff 补齐避免重复累加';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.LAST_RECON_ID IS '最近一次触发的对账记录ID（追溯用）';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.LAST_SHEET_ID IS '最近一次触发的清单ID（追溯用）';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.LAST_ACTION IS '最近一次触发类型：A-新增/M-修改（追溯用）';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FSS_BALANCE_CFG_LOG.UPDATE_TIME IS '更新时间';

CREATE INDEX IDX_CFG_APPLY_LOG_1
    ON FSS_BALANCE_CFG_LOG ( ACCT_NO, CFG_ID, BIZ_DATE );

-- =========================================
-- Table: FSS_BALANCE_CFG_SNP
-- Desc : 日终对账平衡表调整明细表
-- =========================================

CREATE TABLE FSS_BALANCE_CFG_SNP
(
    ITEM_ID       NUMBER(19)              NOT NULL,
    SHEET_ID      NUMBER(19)              NOT NULL,
    SIDE_TYPE     CHAR                    NOT NULL,
    ADJ_TYPE      CHAR                    NOT NULL,
    ITEM_CODE     VARCHAR2(32)            NOT NULL,
    ITEM_NAME     VARCHAR2(128)           NOT NULL,
    AMOUNT        NUMBER(18, 2) DEFAULT 0 NOT NULL,
    CFG_ID        NUMBER(19),
    REASON        VARCHAR2(256),
    DISPLAY_ORDER NUMBER(10)    DEFAULT 0 NOT NULL,

    CONSTRAINT PK_FSS_BALANCE_CFG_SNP PRIMARY KEY ( ITEM_ID )
);

COMMENT ON TABLE FSS_BALANCE_CFG_SNP IS '日终对账平衡表调整明细表';

COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.ITEM_ID IS '主键ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.SHEET_ID IS '所属平衡表ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.SIDE_TYPE IS '所属侧：B-银行 S-系统';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.ADJ_TYPE IS '调整类型：A-应加 S-应减';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.ITEM_CODE IS '调整项编码（配置表）';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.ITEM_NAME IS '调整项名称';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.AMOUNT IS '调整金额';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.CFG_ID IS '来源配置ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.REASON IS '调整原因';
COMMENT ON COLUMN FSS_BALANCE_CFG_SNP.DISPLAY_ORDER IS '显示顺序';

-- =========================================
-- Table: FSS_BALANCE_CFG_BANK
-- Desc : 银行配置项明细表
-- =========================================

ALTER TABLE FSS_BALANCE_CFG_BANK
    ADD (
        CATEGORY VARCHAR2(512)
        );
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.CATEGORY IS '类别';

CREATE TABLE FSS_BALANCE_CFG_BANK
(
    ID          NUMBER(19) DEFAULT 0       NOT NULL,
    CFG_ID      NUMBER(19) DEFAULT 0       NOT NULL,
    WATER_ID    NUMBER(19) DEFAULT 0       NOT NULL,
    CATEGORY    VARCHAR2(512),
    CREATE_TIME DATE       DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_FSS_BALANCE_CFG_BANK PRIMARY KEY ( ID )
);

COMMENT ON TABLE FSS_BALANCE_CFG_BANK IS '银行配置项明细表';
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.ID IS '主键';
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.CFG_ID IS '配置项ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.WATER_ID IS '流水ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.CATEGORY IS '类别';
COMMENT ON COLUMN FSS_BALANCE_CFG_BANK.CREATE_TIME IS '创建时间';

CREATE INDEX IDX_FSS_BALANCE_CFG_BANK_CFG
    ON FSS_BALANCE_CFG_BANK ( CFG_ID );

CREATE INDEX IDX_FSS_BALANCE_CFG_BANK_WATER
    ON FSS_BALANCE_CFG_BANK ( WATER_ID );


-- =========================================
-- Table: FSS_BALANCE_CFG_TRADE
-- Desc : 系统配置项明细表
-- =========================================

CREATE TABLE FSS_BALANCE_CFG_TRADE
(
    ID             NUMBER(19)    DEFAULT 0       NOT NULL,
    CFG_ID         NUMBER(19)    DEFAULT 0       NOT NULL,
    INFO_ID        NUMBER(19)    DEFAULT 0       NOT NULL,
    INFO_ADDR      VARCHAR2(160),
    INFO_AREA      NUMBER(16, 2) DEFAULT 0       NOT NULL,
    BATCH_NO       CHAR(12)                      NOT NULL,
    FUND           NUMBER(19)    DEFAULT 0       NOT NULL,
    TRAN_FLAG      CHAR          DEFAULT '1'     NOT NULL,

    OWN_NAME       VARCHAR2(512),
    OWN_REF        NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_REF_STATUS CHAR(1)       DEFAULT '0'     NOT NULL,
    OWN_INT        NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_INT_STATUS CHAR(1)       DEFAULT '0'     NOT NULL,

    DEW_NAME       VARCHAR2(512),
    DEV_REF        NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_REF_STATUS CHAR(1)       DEFAULT '0'     NOT NULL,
    DEV_INT        NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_INT_STATUS CHAR(1)       DEFAULT '0'     NOT NULL,

    REMARK         VARCHAR2(512),

    CREATE_TIME    DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME    DATE,

    CONSTRAINT PK_FSS_BALANCE_CFG_TRADE PRIMARY KEY ( ID ),

    CONSTRAINT CK_FBCT_OWN_REF_ST CHECK (OWN_REF_STATUS IN ( '0', '1' )),
    CONSTRAINT CK_FBCT_OWN_INT_ST CHECK (OWN_INT_STATUS IN ( '0', '1' )),
    CONSTRAINT CK_FBCT_DEV_REF_ST CHECK (DEV_REF_STATUS IN ( '0', '1' )),
    CONSTRAINT CK_FBCT_DEV_INT_ST CHECK (DEV_INT_STATUS IN ( '0', '1' ))
);

COMMENT ON TABLE FSS_BALANCE_CFG_TRADE IS '系统配置项明细表';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.ID IS '主键';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CFG_ID IS '配置项ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ID IS '信息ID';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ADDR IS '信息地址';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_AREA IS '分户面积';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.BATCH_NO IS '退款批次号';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.FUND IS '资金账号';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.TRAN_FLAG IS '借贷表示';

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_NAME IS '购房人姓名';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF IS '购房人退款本金';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF_STATUS IS '购房人退款本金状态(0未处理/1已处理)';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT IS '购房人退款利息';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT_STATUS IS '购房人退款利息状态(0未处理/1已处理)';

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEW_NAME IS '开发商名称';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF IS '开发商退款本金';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF_STATUS IS '开发商退款本金状态(0未处理/1已处理)';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT IS '开发商退款利息';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT_STATUS IS '开发商退款利息状态(0未处理/1已处理)';

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.REMARK IS '备注';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.UPDATE_TIME IS '更新时间';

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_CFG
    ON FSS_BALANCE_CFG_TRADE ( CFG_ID );

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_INFO
    ON FSS_BALANCE_CFG_TRADE ( INFO_ID );

CREATE SEQUENCE SEQ_FSS_BALANCE_CFG_TRADE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

ALTER TABLE FSS_BALANCE_CFG_TRADE
    MODIFY (
        INFO_ID NULL,
        INFO_AREA NULL,
        BATCH_NO NULL,
        FUND NULL
        );

ALTER TABLE FSS_BALANCE_CFG_TRADE
    ADD
        (
        SOURCE_TYPE VARCHAR2(16),
        CATEGORY CHAR(2),
        DIST_ID NUMBER(19) DEFAULT 0,
        SECT_ID NUMBER(19) DEFAULT 0,
        OWN_CERT_TYPE CHAR(2),
        OWN_CERT_CODE VARCHAR2(1024),
        PRODUCE_DATE CHAR(8),
        RAW_DETAIL_INFO VARCHAR2(2000),
        TRAN_AMT NUMBER(16, 2)
        )
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.SOURCE_TYPE IS '来源文件名称'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CATEGORY IS '类别'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.REGION_ID IS '所属区'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DIST_ID IS '项目信息Id'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_TYPE IS '购房人证件类型'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_CODE IS '购房人证件号码'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.PRODUCE_DATE IS '产生日期'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.RAW_DETAIL_INFO IS '原始明细信息'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.TRAN_AMT IS '总待退金额=未处理开发商本金+未处理开发商利息+未处理购房人本金+未处理购房人利息'
/


CREATE TABLE FSS_BALANCE_CFG_TRADE
(
    ID              NUMBER(19)    DEFAULT 0       NOT NULL
        CONSTRAINT PK_FSS_BALANCE_CFG_TRADE
            PRIMARY KEY,
    CFG_ID          NUMBER(19)    DEFAULT 0       NOT NULL,
    SOURCE_TYPE     VARCHAR2(128),
    CATEGORY        VARCHAR2(16),
    SECT_ID         NUMBER(19)    DEFAULT 0,
    TRAN_AMT        NUMBER(16, 2),

    INFO_ID         NUMBER(19)    DEFAULT 0,
    INFO_ADDR      VARCHAR2(512),
    OWN_NAME        VARCHAR2(512),
    OWN_CERT_TYPE   CHAR(2),
    OWN_CERT_CODE   VARCHAR2(1024),
    OWN_REF         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_REF_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_OWN_REF_ST
            CHECK (OWN_REF_STATUS IN ( '0', '1' )),
    OWN_INT         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    OWN_INT_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_OWN_INT_ST
            CHECK (OWN_INT_STATUS IN ( '0', '1' )),
    DEV_NAME        VARCHAR2(512),
    DEV_REF         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_REF_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_DEV_REF_ST
            CHECK (DEV_REF_STATUS IN ( '0', '1' )),
    DEV_INT         NUMBER(16, 2) DEFAULT 0       NOT NULL,
    DEV_INT_STATUS  CHAR          DEFAULT '0'     NOT NULL
        CONSTRAINT CK_FBCT_DEV_INT_ST
            CHECK (DEV_INT_STATUS IN ( '0', '1' )),
    REMARK          VARCHAR2(512),
    CREATE_TIME     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME     DATE,

    PRODUCE_DATE    CHAR(8),
    RAW_DETAIL_INFO VARCHAR2(2000)
)
/

COMMENT ON TABLE FSS_BALANCE_CFG_TRADE IS '系统配置项明细表'
/

COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.ID IS '主键'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CFG_ID IS '配置项ID'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.SOURCE_TYPE IS '来源文件名称'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CATEGORY IS '类别'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.SECT_ID IS '项目信息Id'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_TYPE IS '购房人证件类型'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_CERT_CODE IS '购房人证件号码'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.TRAN_AMT IS '总待退金额=未处理开发商本金+未处理开发商利息+未处理购房人本金+未处理购房人利息'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ID IS '信息ID'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.INFO_ADDR IS '地址';
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.TRAN_FLAG IS '借贷表示'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_NAME IS '购房人姓名'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF IS '购房人退款本金'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF_STATUS IS '购房人退款本金状态(0未处理/1已处理)'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT IS '购房人退款利息'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT_STATUS IS '购房人退款利息状态(0未处理/1已处理)'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEW_NAME IS '开发商名称'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF IS '开发商退款本金'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF_STATUS IS '开发商退款本金状态(0未处理/1已处理)'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT IS '开发商退款利息'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT_STATUS IS '开发商退款利息状态(0未处理/1已处理)'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.REMARK IS '备注'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.PRODUCE_DATE IS '产生日期'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.CREATE_TIME IS '创建时间'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.UPDATE_TIME IS '更新时间'
/
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.RAW_DETAIL_INFO IS '原始明细信息'
/

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_CFG
    ON FSS_BALANCE_CFG_TRADE ( CFG_ID )
/

CREATE INDEX IDX_FSS_BALANCE_CFG_TRADE_INFO
    ON FSS_BALANCE_CFG_TRADE ( INFO_ID )
/

ALTER TABLE HX_WATER_DETAIL
    ADD (
        CREATE_TYPE CHAR(1) DEFAULT '0'
        );
COMMENT ON COLUMN HX_WATER_DETAIL.CREATE_TYPE IS '来源：0-同步，1-手工';

INSERT INTO HX_WATER_DETAIL (
    ID,
    BASE_ACCT_NO,
    TRAN_AMT,
    CREATE_TYPE,
    TRAN_NOTE,
    TRAN_NOTE_BIZ
) VALUES (
             1000000000001,
             '158001201110000869',
             126278.00,
             '1',
             '浩天源',
             '浩天源'
         );

INSERT INTO HX_WATER_DETAIL (
    ID,
    BASE_ACCT_NO,
    TRAN_AMT,
    CREATE_TYPE,
    TRAN_NOTE,
    TRAN_NOTE_BIZ
) VALUES (
             1000000000002,
             '158001201110000869',
             8883839.7,
             '1',
             '拟造',
             '拟造'
         );
