UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 465;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 468;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 469;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 467;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 460;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20091125' WHERE t.ID = 486;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 461;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20251021' WHERE t.ID = 453;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20251021' WHERE t.ID = 455;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20251021' WHERE t.ID = 454;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20091116' WHERE t.ID = 483;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 462;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20091124' WHERE t.ID = 478;
UPDATE HMFMSFD.FSS_BALANCE_CFG_TRADE t SET t.PRODUCE_DATE = '20191021' WHERE t.ID = 466;

UPDATE FSS_BALANCE_CFG_TRADE
SET OWN_REF_STATUS = CASE WHEN OWN_REF = 0 THEN '2' ELSE OWN_REF_STATUS END,
    OWN_INT_STATUS = CASE WHEN OWN_INT = 0 THEN '2' ELSE OWN_INT_STATUS END,
    DEV_REF_STATUS = CASE WHEN DEV_REF = 0 THEN '2' ELSE DEV_REF_STATUS END,
    DEV_INT_STATUS = CASE WHEN DEV_INT = 0 THEN '2' ELSE DEV_INT_STATUS END,
    UPDATE_TIME    = SYSDATE -- 建议同步更新时间戳
WHERE ( OWN_REF = 0 AND OWN_REF_STATUS <> '2' )
   OR ( OWN_INT = 0 AND OWN_INT_STATUS <> '2' )
   OR ( DEV_REF = 0 AND DEV_REF_STATUS <> '2' )
   OR ( DEV_INT = 0 AND DEV_INT_STATUS <> '2' );