-- 1) 先删除旧的 CHECK 约束（只允许 0/1）
ALTER TABLE FSS_BALANCE_CFG_TRADE DROP CONSTRAINT CK_FBCT_OWN_REF_ST;
ALTER TABLE FSS_BALANCE_CFG_TRADE DROP CONSTRAINT CK_FBCT_OWN_INT_ST;
ALTER TABLE FSS_BALANCE_CFG_TRADE DROP CONSTRAINT CK_FBCT_DEV_REF_ST;
ALTER TABLE FSS_BALANCE_CFG_TRADE DROP CONSTRAINT CK_FBCT_DEV_INT_ST;

-- 2) 重新加 CHECK 约束（允许 0/1/2）
ALTER TABLE FSS_BALANCE_CFG_TRADE ADD CONSTRAINT CK_FBCT_OWN_REF_ST
    CHECK (OWN_REF_STATUS IN ('0','1','2'));

ALTER TABLE FSS_BALANCE_CFG_TRADE ADD CONSTRAINT CK_FBCT_OWN_INT_ST
    CHECK (OWN_INT_STATUS IN ('0','1','2'));

ALTER TABLE FSS_BALANCE_CFG_TRADE ADD CONSTRAINT CK_FBCT_DEV_REF_ST
    CHECK (DEV_REF_STATUS IN ('0','1','2'));

ALTER TABLE FSS_BALANCE_CFG_TRADE ADD CONSTRAINT CK_FBCT_DEV_INT_ST
    CHECK (DEV_INT_STATUS IN ('0','1','2'));

-- 3) 更新字段注释
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_REF_STATUS IS '购房人退款本金状态(0未处理/1处理中/2已处理)';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.OWN_INT_STATUS IS '购房人退款利息状态(0未处理/1处理中/2已处理)';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_REF_STATUS IS '开发商退款本金状态(0未处理/1处理中/2已处理)';
COMMENT ON COLUMN FSS_BALANCE_CFG_TRADE.DEV_INT_STATUS IS '开发商退款利息状态(0未处理/1处理中/2已处理)';

UPDATE FSS_BALANCE_CFG_TRADE
SET
    OWN_REF_STATUS = CASE WHEN OWN_REF_STATUS = '1' THEN '2' ELSE OWN_REF_STATUS END,
    OWN_INT_STATUS = CASE WHEN OWN_INT_STATUS = '1' THEN '2' ELSE OWN_INT_STATUS END,
    DEV_REF_STATUS = CASE WHEN DEV_REF_STATUS = '1' THEN '2' ELSE DEV_REF_STATUS END,
    DEV_INT_STATUS = CASE WHEN DEV_INT_STATUS = '1' THEN '2' ELSE DEV_INT_STATUS END
WHERE
    OWN_REF_STATUS = '1'
   OR OWN_INT_STATUS = '1'
   OR DEV_REF_STATUS = '1'
   OR DEV_INT_STATUS = '1';